### ISSUE TITLE
Carousel Bug

### ISSUE THREAD

**Issue by javad0470** [stevdza-san/KotlinBootstrap#12]
hello dear stefan I came to thank you for your great library, and also to report a bug in Carousel that I would appreciate if you could look into.

{
    "message": "Function 'width' can not be called: No function found for symbol 'com.varabyte.kobweb.compose.ui.modifiers/width|width@com.varabyte.kobweb.compose.ui.Modifier(org.jetbrains.compose.web.css.CSSNumericValue<out|org.jetbrains.compose.web.css.CSSUnit>){}[0]'",
    "name": "IrLinkageError"
}

**Comment by stevdza-san** [comment]
Thanks for your report, I'll check it out. Could you please describe what parameters have you passed to the Carousel function, if you have? It would be great if you could share a sample code, so that I can try to reproduce the issue. 

Also, try updating your versions to: Kobweb **0.15.4**, Kotlin **1.9.21**, and Compose **1.5.11** and see if the issue still persists. :)

**Comment by javad0470** [comment]
exactly like your example but inside a box

**Comment by stevdza-san** [comment]
Have you tried updating the versions that I've mentioned in the previous comment?

**Comment by javad0470** [comment]
Yes, the project is already updated

**Comment by stevdza-san** [comment]
Thanks, I'll take a look at it at the end of the week.

**Comment by stevdza-san** [comment]
I've just tested a Carousel component placed inside the Box, and it works on my end:

``` kotlin
 Box {
        BSCarousel(
            items = listOf(
                CarouselItem(
                    image = "https://images.pexels.com/photos/2662116/pexels-photo-2662116.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                    title = "Moraine Lake"
                ),
                CarouselItem(
                    image = "https://images.pexels.com/photos/147411/italy-mountains-dawn-daybreak-147411.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                    title = "Italy"
                ),
                CarouselItem(
                    image = "https://images.pexels.com/photos/1166209/pexels-photo-1166209.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                    title = "Lavender"
                ),
            ),
            width = 900.px,
            height = 500.px
        )
    }
```
