### ISSUE TITLE
Page become blank, when I add any bootstrap element

### ISSUE THREAD

**Issue by Stipsaa** [stevdza-san/KotlinBootstrap#15]
When I add any bootstrap element, BSDropdown() for example, my page become totally blank and empty. Could you help, please?

```
@Page
@Composable
fun HomePage() {
    Column(
        modifier = Modifier.fillMaxSize(),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        BSDropdown(
            placeholder = "Select a Platform",
            items = listOf("Android", "iOS", "Web"),
            onItemSelect = { index, value -> }
        )

        SpanText("Some text")
    }
}
```

![image](https://github.com/stevdza-san/KotlinBootstrap/assets/102070473/ac4f4aff-8df2-40a6-817b-03f13ec51992)

**Comment by stevdza-san** [comment]
What versions are you using exactly, for kotlin, compose, and kobweb?

**Comment by Stipsaa** [comment]
> What versions are you using exactly, for kotlin, compose, and kobweb?

jetbrains-compose = "1.6.1"
kobweb = "0.17.1"
kotlin = "1.9.23"

**Comment by stevdza-san** [comment]
Try these version and let me know if it works:

jetbrains-compose = "1.5.12"
kobweb = "0.16.1"
kotlin = "1.9.22"

**Comment by Stipsaa** [comment]
> Try these version and let me know if it works:
> 
> jetbrains-compose = "1.5.12" kobweb = "0.16.1" kotlin = "1.9.22"

It helped! TY
