### ISSUE TITLE
How to use a general application theme?

### ISSUE THREAD

**Issue by N7ghtm4r3** [stevdza-san/KotlinBootstrap#16]
Hi, it is possible use a general application theme like MaterialTheme function for the all application components?
For example export the theme from [Material Theme Builder](https://material-foundation.github.io/material-theme-builder/) or include it as:
 
```html
<link rel="stylesheet" href="mystyle.css">
```

**Comment by stevdza-san** [comment]
Similarly that's how this library is made. You can check the build.gradle file and see where I've declared all those styles. :)

**Comment by N7ghtm4r3** [comment]
Thank you, I will check for sure!

**Comment by N7ghtm4r3** [comment]
Sorry, I tried  to check this [build.gradle.kts](https://github.com/stevdza-san/KotlinBootstrap/blob/master/bootstrap/build.gradle.kts) hoping that was the correct one, but how can I use then after adding to the gradle? For example how can I use the primary color of the general theme in the css for the background color of the [NavBar](https://github.com/stevdza-san/KotlinBootstrap?tab=readme-ov-file#navbar) component

**Comment by stevdza-san** [comment]
You can add those custom css styles in your code, like this for example: https://github.com/stevdza-san/KotlinBootstrap/blob/master/bootstrap/src/jsMain/kotlin/com/stevdza/san/kotlinbs/components/BSButton.kt#L102

**Comment by N7ghtm4r3** [comment]
Thank you! I will take a look and implement the theme following your code

**Comment by N7ghtm4r3** [comment]
Hi, sorry again, I tried to figure out how to change the color following the code you shared, but in the specific case of the [BSNavBar](https://github.com/stevdza-san/KotlinBootstrap?tab=readme-ov-file#navbar) component I'm not figured out how to set a custom color for the background, because the `backgroundStyle` uses specific colors, is there a way to set a custom color overriding that parameter? Thank you again

**Comment by stevdza-san** [comment]
I haven't added a support for more customization options.

**Comment by N7ghtm4r3** [comment]
Okay I understood, thank you for the reply, but it is planned?
