### ISSUE TITLE
Not compatible with kotlin 1.9.23 & kobweb: 0.17.1

### ISSUE THREAD

**Issue by Dev-Husnain** [stevdza-san/KotlinBootstrap#17]
I was trying to run on Kotlin 1.9.23, Kobweb 0.17.1 and compose:1.6.1 ang got below exception

cause
: 
undefined
message
: 
"Function 'BSSpinner' can not be called: No function found for symbol 'com.stevdza.san.kotlinbs.components/BSSpinner|BSSpinner(com.varabyte.kobweb.compose.ui.Modifier?;com.stevdza.san.kotlinbs.models.SpinnerStyle?;com.stevdza.san.kotlinbs.models.SpinnerVariant?;androidx.compose.runtime.Composer?;kotlin.Int;kotlin.Int){}[0]'"
name
: 
"IrLinkageError"

**Comment by javad0470** [comment]
yeah please update the project root

**Comment by stevdza-san** [comment]
Done with the newest version.
