### ISSUE TITLE
Is this project open for contribution?

### ISSUE THREAD

**Issue by DrProNoob** [stevdza-san/KotlinBootstrap#23]
Is this project open for contribution?

**Comment by bitspittle** [comment]
I filed a few PRs in the past. I don't want to speak for Stevdza-san, but if you have something specific in mind, especially if it's relatively straightforward, I'd suggest going for it!

**Comment by stevdza-san** [comment]
@DrProNoob Oh yeah, feel free to involve! :)

**Comment by stevdza-san** [comment]
@bitspittle Definitely, this is an open source project after all. 👍
