### ISSUE TITLE
Support Video

### ISSUE THREAD

**Issue by Micoder-dev** [stevdza-san/KotlinBootstrap#5]
Can we include video players that play URLs like local resource mp4, online videos like HLS etc...  something alternative like Exoplayer which we are using in Android.

**Comment by bitspittle** [comment]
Up to Stevdza-san but this is probably not something should get added in this library. This library is bindings into bootstrap components, which you can see the full list here: https://getbootstrap.com/docs/5.3/components/

You probably want to just use the video element that's part of HTML and included in Compose HTML.

**Comment by stevdza-san** [comment]
@bitspittle Yes, that's correct, thanks for explaining it to @Micoder-dev . That's already possible without the need for bootstrap. :)
