### ISSUE TITLE
BSDropdown has no way to control the initial selection

### ISSUE THREAD

**Issue by hduden** [stevdza-san/KotlinBootstrap#6]
BSDropdown only takes a list of items and a placeholder value. Unless I am mistaken there is no way to control the initially selected item from outside.
Internally, the first item in the list is preselected if not placeholder is provided. However, if the first item is preselected this way then it is not highlighted in the dropdown menu.

Expected behaviour:
There should be an optional parameter that either takes an index or a string value to control the initially selected item. Also, when this parameter is not provided and the placeholder is missing (i.e. when the first item is auto-selected) then the selected item should be highlighted in the dropdown menu.

**Comment by stevdza-san** [comment]
I've added a default logic that the first element in the list will be the one which is selected. Thanks for your suggestion, I'll consider adding an additional parameter. Will leave this issue open for the time-being.

**Comment by stevdza-san** [comment]
I've fixed this issue in the new v0.0.8 version. Now there's a new additional selectedItem parameter that you can customize.

**Comment by hduden** [comment]
Thank you for solving this so quickly. Very much appreciated 🙂
